GET http://localhost:5147/games

###

GET http://localhost:5147/games/2

###

POST http://localhost:5147/games
Content-Type: application/json

{
  "name": "TEST GAME",
  "genreId": 4,
  "price": 39.99,
  "releaseDate": "2024-06-01"
}

###

PUT http://localhost:5147/games/2
Content-Type: application/json

{
  "name": "Dark Souls III",
  "genreId": 1,
  "price": 29.99,
  "releaseDate": "2010-05-18"
}

###

DELETE http://localhost:5147/games/4

###

GET http://localhost:5147/genres